<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-GGCLQ1N" failures="1" tests="4" name="ui.ReportsTest" time="1.821" errors="0" timestamp="2022-10-04T19:14:28 SGT" skipped="0">
  <testcase classname="ui.ReportsTest" name="reportTest2" time="0.002"/>
  <system-out>
Test Name is - reportTest2 This is Test 2. Status of Test is - 1  </system-out>
  <testcase classname="ui.ReportsTest" name="reportTest4" time="0.003"/>
  <system-out>
Test Name is - reportTest4 Status of Test is - 1  </system-out>
  <testcase classname="ui.ReportsTest" name="reportTest1" time="1.813">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.fail(Assert.java:102)
at ui.ReportsTest.reportTest1(ReportsTest.java:15)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- reportTest1 -->
  <system-out>
Test Name is - reportTest1 Test failed - screenshot captured.  <a href="C:\Users\shank\eclipse-workspace\seleniumTesting\screenshot\Tue-Oct-04-19-14-26-SGT-2022.png">Test Results</a>  </system-out>
  <testcase classname="ui.ReportsTest" name="reportTest3" time="0.003"/>
  <system-out>
Test Name is - reportTest3 This is Test 3. Status of Test is - 1  </system-out>
</testsuite> <!-- ui.ReportsTest -->
